import type { Moment } from './types'

// Launch set. One idea per card, reading age 12, four beats: what is
// happening, what is normal, what to do, when to escalate. Sources named.
export const MOMENTS: Moment[] = [
  {
    id: 'how-glp1-works',
    title: 'How GLP-1 medicines actually work',
    hook: 'One minute on what the injection is doing, so the rest makes sense.',
    readSeconds: 60,
    trigger: 'onboarding_complete',
    priority: 4,
    cooldownDays: 365,
    tag: 'starting',
    body: [
      'GLP-1 is a hormone your gut releases after you eat. Mounjaro, Wegovy and Ozempic copy it and stay in your body for days instead of minutes.',
      '**What it does:** slows how fast your stomach empties, tells your brain you are full, and steadies blood sugar. Most people describe it as the "food noise" going quiet.',
      '**What it does not do:** choose what you eat, protect your muscle, or fix sleep. Those are yours, and this app exists to make them easy.',
      '**The one thing to know today:** weight lost on these medicines can be up to 40% lean mass if protein and resistance training are neglected. Protein is the biggest ring on your home screen for that reason.',
    ],
    sources: ['NICE TA875 and TA1026', 'Wilding et al., NEJM 2021 (STEP 1)', 'Jastreboff et al., NEJM 2022 (SURMOUNT-1)'],
    check: {
      question: 'What is the biggest risk this app is built to reduce?',
      options: ['Losing weight too slowly', 'Losing muscle along with fat', 'Injection site bruising'],
      correct: 1,
      explain: 'Up to 40% of weight lost can be lean mass. Protein and two lifts a week are the insurance policy.',
    },
    guideId: 'starting-glp1-uk',
  },
  {
    id: 'site-rotation',
    title: 'Rotate your injection sites',
    hook: 'Same spot every week is how you get lumps. Here is the simple rule.',
    readSeconds: 45,
    trigger: 'first_shot_logged',
    priority: 4,
    cooldownDays: 365,
    tag: 'injections',
    body: [
      '**Why:** injecting the same spot repeatedly can cause lipohypertrophy, a firm fatty lump that absorbs medicine unevenly.',
      '**The rule:** six zones, abdomen left and right, thigh left and right, upper arm left and right. Move to a different zone each shot and stay at least 2 to 3 cm from the last mark within a zone.',
      '**Abdomen:** keep 5 cm clear of the belly button.',
      'The app suggests the least-recently-used site on your shot card. You can override it.',
    ],
    sources: ['Mounjaro and Wegovy patient leaflets', 'FIT UK injection technique recommendations'],
    check: {
      question: 'How far from the belly button should abdominal injections be?',
      options: ['1 cm', '5 cm', 'It does not matter'],
      correct: 1,
      explain: 'Five centimetres clear, and rotate between the six zones.',
    },
    guideId: 'injection-technique',
  },
  {
    id: 'step-up-72h',
    title: 'The 72 hours after a step-up',
    hook: 'You moved up a dose. Here is what is normal and what is not.',
    readSeconds: 60,
    trigger: 'titration_step_up',
    priority: 5,
    cooldownDays: 21,
    tag: 'side_effects',
    body: [
      'Weekly GLP-1 medicines peak in your blood around day 2 to 3 after the injection, so that is when a new dose is most likely to cause nausea and tiredness.',
      '**Normal:** mild nausea, feeling full faster, less interest in food, a flat day or two.',
      '**Do:** small meals, protein first, go easy on fat, sip water through the day rather than big glasses. Keep the shot on the same weekday.',
      '**Ask your prescriber:** vomiting that stops you keeping fluids down, severe stomach pain, or nausea that has not eased by day 5.',
    ],
    prescriberPrompt: 'Tell your prescriber if side effects after a step-up last beyond a week. Staying on the lower dose for longer is a normal option.',
    sources: ['Mounjaro SmPC section 4.8', 'Wegovy SmPC section 4.8'],
    check: {
      question: 'When is a new dose most likely to cause nausea?',
      options: ['The first evening', 'Day 2 to 3', 'Day 7'],
      correct: 1,
      explain: 'Blood levels peak two to three days after the injection.',
    },
    guideId: 'side-effect-playbook',
  },
  {
    id: 'nausea-playbook',
    title: 'The nausea playbook',
    hook: 'Four things that reliably take the edge off, and one that makes it worse.',
    readSeconds: 60,
    trigger: 'side_effect_nausea',
    priority: 4,
    cooldownDays: 14,
    tag: 'side_effects',
    body: [
      '**Portion:** half of what you used to plate. Stop at "not hungry", not "full". Your stomach empties slowly now and overfilling it is the main trigger.',
      '**Fat and sugar:** greasy, fried and very sweet foods sit longest. Save them for non-shot days if at all.',
      '**Timing:** eat slowly, and do not lie down for an hour after a meal. Ginger tea and plain crackers help many people.',
      '**Water:** small sips all day. Big glasses on a full stomach make it worse.',
      '**What makes it worse:** skipping meals entirely. An empty stomach with GLP-1 on board is often more nauseous than a small meal.',
    ],
    prescriberPrompt: 'If nausea stops you eating or drinking for more than a day, contact your prescriber. Anti-sickness medicine is an option they can discuss.',
    sources: ['Wharton et al., Postgraduate Medicine 2022, GI side-effect management on GLP-1 RAs'],
    guideId: 'side-effect-playbook',
  },
  {
    id: 'constipation-fix',
    title: 'Constipation: fibre, water, movement',
    hook: 'Slower digestion is the point of the medicine. This is how to keep things moving.',
    readSeconds: 50,
    trigger: 'side_effect_constipation',
    priority: 3,
    cooldownDays: 14,
    tag: 'side_effects',
    body: [
      '**Fibre:** aim for 25 to 30 g a day. Oats, beans, lentils, berries, vegetables. Add it gradually or it backfires.',
      '**Water:** 2 litres or more. Fibre without water makes constipation worse.',
      '**Movement:** a 15-minute walk after meals genuinely helps gut motility.',
      '**If it persists:** an over-the-counter osmotic laxative such as macrogol is what most prescribers suggest first. Ask them.',
    ],
    prescriberPrompt: 'No bowel movement for 3 or more days, or pain and bloating, is worth a call to your prescriber or GP.',
    sources: ['NHS constipation guidance', 'Wegovy SmPC section 4.8'],
    guideId: 'side-effect-playbook',
  },
  {
    id: 'fatigue-loop',
    title: 'The fatigue loop',
    hook: 'Tired on GLP-1 is usually three things, and all three are fixable.',
    readSeconds: 50,
    trigger: 'side_effect_fatigue',
    priority: 3,
    cooldownDays: 14,
    tag: 'side_effects',
    body: [
      '**Under-eating:** eating far below your needs for days is the most common cause. Protein target first, then enough total food to function.',
      '**Sleep:** short or broken sleep raises hunger hormones and drains energy. Check the Sleep tab for the last three nights.',
      '**Hydration and salt:** less food means less salt and water coming in. A pinch of salt in water or a broth helps more than people expect.',
      'If fatigue is severe, persistent, or comes with dizziness or a racing heart, tell your prescriber.',
    ],
    sources: ['Mounjaro SmPC section 4.8', 'NHS tiredness and fatigue guidance'],
    guideId: 'side-effect-playbook',
  },
  {
    id: 'protein-insurance',
    title: 'Protein is the muscle insurance policy',
    hook: 'Three days under target. This is why it matters and the easiest way back.',
    readSeconds: 60,
    trigger: 'protein_under_target_3_days',
    priority: 4,
    cooldownDays: 7,
    tag: 'protein',
    body: [
      'When you eat less, your body takes energy from both fat and muscle. Protein plus resistance training tells it to keep the muscle.',
      '**Target:** 1.2 to 1.6 g per kg of body weight. Yours is set on the Food tab.',
      '**The easy wins:** Greek yoghurt, eggs, cottage cheese, chicken, fish, tofu, a whey or pea shake. One shake is 20 to 25 g and closes most gaps.',
      '**Protein first:** eat the protein on the plate before anything else. With a smaller appetite, the order matters.',
    ],
    sources: ['Phillips et al., Br J Nutr 2012', 'ESPEN guidance on protein in weight loss'],
    check: {
      question: 'Roughly how much protein is in one scoop of whey?',
      options: ['5 to 10 g', '20 to 25 g', '50 g'],
      correct: 1,
      explain: 'About 20 to 25 g, which closes most daily gaps.',
    },
    guideId: 'protein-on-glp1',
  },
  {
    id: 'two-lifts',
    title: 'Two sessions a week is enough',
    hook: 'No training logged in two weeks. Here is the minimum that protects muscle.',
    readSeconds: 50,
    trigger: 'no_training_14_days',
    priority: 3,
    cooldownDays: 14,
    tag: 'muscle',
    body: [
      'Resistance training is the second half of keeping muscle. It does not need a gym or an hour.',
      '**The minimum:** two sessions a week, 20 to 30 minutes, covering push (press-ups or dumbbell press), pull (rows), legs (squats or sit-to-stand), and a carry or plank.',
      '**Effort:** the last two reps of each set should feel hard. That is the signal your muscle needs.',
      'Log it in one tap on the Today screen. The app only counts, it does not judge.',
    ],
    sources: ['UK CMO physical activity guidelines 2019', 'Weiss et al., Obesity 2017'],
    guideId: 'keeping-muscle',
  },
  {
    id: 'plateau-normal',
    title: 'Plateaus are normal',
    hook: 'Three weeks flat. What to check before changing anything.',
    readSeconds: 60,
    trigger: 'weight_plateau_21_days',
    priority: 3,
    cooldownDays: 21,
    tag: 'plateaus',
    body: [
      'Weight loss on GLP-1 comes in steps, not a straight line. A flat three weeks is common, especially before a dose step-up or after a fast few weeks.',
      '**Check first:** are you logging most meals? Has protein slipped? Are you sleeping under 6 hours? Has your water dropped? Any of those can stall you.',
      '**Check second:** waist measurement and how clothes fit. Muscle gain with fat loss can hold the scale still while you are getting leaner.',
      '**Do not:** cut calories hard or skip meals. That costs muscle. Talk to your prescriber about the next titration step if you are at week 4 or more on this dose.',
    ],
    sources: ['STEP and SURMOUNT trial weight trajectories', 'NICE TA1026'],
    guideId: 'plateaus',
  },
  {
    id: 'short-sleep-ghrelin',
    title: 'Short sleep raises hunger hormones',
    hook: 'Three nights under six hours. Fix bedtime before touching breakfast.',
    readSeconds: 50,
    trigger: 'sleep_under_6h_3_nights',
    priority: 4,
    cooldownDays: 7,
    tag: 'sleep',
    body: [
      'One short night raises ghrelin (hunger) and lowers leptin (fullness) the next day. Three in a row and cravings climb, willpower drops and muscle recovery stalls.',
      '**Tonight:** pick a bedtime that gives 7 hours before your alarm and set it in the Sleep tab. The app will dim itself an hour before.',
      '**The three that work:** same wake time every day, no big meal or alcohol within 3 hours of bed, screens down 30 minutes before.',
      '**Shot night:** many people sleep worse the night after their injection. If that is you, try dosing in the morning.',
    ],
    sources: ['Spiegel et al., Ann Intern Med 2004', 'Nedeltcheva et al., Ann Intern Med 2010'],
    guideId: 'sleep-and-weight-loss',
  },
  {
    id: 'missed-dose',
    title: 'You missed a dose. Here is the manufacturer guidance',
    hook: 'The rule depends on the medicine. Read it, then decide with your prescriber.',
    readSeconds: 40,
    trigger: 'missed_dose',
    priority: 5,
    cooldownDays: 3,
    tag: 'injections',
    body: [
      '**Mounjaro (tirzepatide):** take it within 4 days of the missed dose. Past 4 days, skip and take the next one on schedule. Never two doses within 3 days.',
      '**Wegovy (semaglutide):** take it if the next dose is more than 2 days away. Otherwise skip.',
      '**Ozempic (semaglutide):** take it within 5 days. Past 5 days, skip.',
      'This is the manufacturer guidance, not advice from this app. If you have missed two or more doses, ask your prescriber whether to restart at a lower dose.',
    ],
    sources: ['Mounjaro SmPC section 4.2', 'Wegovy SmPC section 4.2', 'Ozempic SmPC section 4.2'],
    guideId: 'injection-technique',
  },
  {
    id: 'unlicensed-harm-reduction',
    title: 'No licensed supply exists for this compound',
    hook: 'You added an unlicensed compound. Read this before the first vial.',
    readSeconds: 60,
    trigger: 'unlicensed_compound_added',
    priority: 5,
    cooldownDays: 365,
    tag: 'peptides',
    body: [
      'Retatrutide and similar research compounds are not approved in the UK, US or EU. Anything sold online as "research peptide" has no MHRA quality control. Contamination, wrong strength and mislabelling are documented.',
      '**If you proceed anyway:** use a fresh sterile needle every time, keep reconstituted vials refrigerated and use within 28 days, never share vials, and check the vial for cloudiness or particles before every draw.',
      '**Red flags that need a doctor:** fever, redness spreading from the injection site, a racing heart, fainting, or vomiting you cannot control.',
      'This app will track doses for you and show the calculator working. It will not suggest a dose or a schedule for an unlicensed compound.',
    ],
    sources: ['MHRA enforcement notice, October 2025', 'MHRA guidance on unlicensed medicines'],
    guideId: 'peptides-harm-reduction',
  },
  {
    id: 'shot-day-eating',
    title: 'Shot day eating',
    hook: 'Small portions, protein first, easy on fat. That is the whole rule.',
    readSeconds: 30,
    trigger: 'shot_day',
    priority: 2,
    cooldownDays: 14,
    tag: 'side_effects',
    body: [
      'The day of and the day after your injection are when the medicine is climbing in your blood. Meals that are small, protein-led and low in fat are the least likely to come back to haunt you.',
      '**A good shot-day plate:** eggs or yoghurt in the morning, chicken or fish with vegetables later, a shake if protein is short. Skip the takeaway.',
    ],
    sources: ['Wharton et al., Postgraduate Medicine 2022'],
  },
  {
    id: 'week-12-maintenance',
    title: 'Maintenance thinking starts now',
    hook: 'Twelve weeks in. The habits you build now are what keep the weight off later.',
    readSeconds: 60,
    trigger: 'week_12_reached',
    priority: 3,
    cooldownDays: 365,
    tag: 'plateaus',
    body: [
      'Most people regain a large share of lost weight within a year of stopping GLP-1 medicines if nothing else changed. The ones who keep it off built habits while the medicine made them easy.',
      '**The four that matter:** protein at target most days, two resistance sessions a week, 7 hours of sleep, and a way of eating you would happily do without the medicine.',
      'You do not need to plan stopping now. You do need to notice which of those four is not yet a habit.',
    ],
    sources: ['Wilding et al., Diabetes Obes Metab 2022 (STEP 1 extension)', 'Aronne et al., JAMA 2024 (SURMOUNT-4)'],
    guideId: 'maintenance',
  },
  {
    id: 'why-night-mode',
    title: 'Why the app dims at night',
    hook: 'Warm colours, no red, nothing shouting. It is on purpose.',
    readSeconds: 30,
    trigger: 'night_mode_first',
    priority: 1,
    cooldownDays: 365,
    tag: 'app',
    body: [
      'After 9 pm the app switches to a warm, low-contrast palette and stops using red. Bright, cool light and alarming colours late in the evening push bedtime later.',
      'You can change the hours in Settings. The shot reminder still comes through.',
    ],
    sources: ['Chang et al., PNAS 2015, evening light exposure and sleep'],
  },
  {
    id: 'reading-bloods',
    title: 'What your bloods can and cannot tell you',
    hook: 'You added results. Here is how to read them without panicking.',
    readSeconds: 60,
    trigger: 'bloodwork_added',
    priority: 3,
    cooldownDays: 60,
    tag: 'starting',
    body: [
      'A single result outside the range is a prompt for a question, not a verdict. Labs differ, samples vary, and a cold or a hard workout can nudge several markers.',
      '**Look for direction:** the change since your last test matters more than one number. The app lines results up by date for that reason.',
      '**The ones GLP-1 tends to improve:** HbA1c, triglycerides, ALT, CRP. **The ones to watch as you eat less:** ferritin, B12, vitamin D.',
      '**Take it to your GP:** anything flagged, plus the question "what would you like repeated and when?"',
    ],
    prescriberPrompt: 'Ask which flagged results matter and which are noise.',
    sources: ['NHS lab reference ranges', 'NICE NG28'],
    guideId: 'reading-your-bloodwork',
  },
]

export function momentById(id: string): Moment | undefined {
  return MOMENTS.find(m => m.id === id)
}
